### ISSUE TITLE
Permission denied for MaryTTS Installer v5.1.2

### ISSUE THREAD

**Issue by blsn** [marytts/marytts-installer#2]
I'm trying to use MaryTTS Installer v5.1.2 on CentOS 6 64bit.
Installed: Java jdk1.8.0_45 & apache-maven-3.0.5

I downloaded the latest source code package, and I followed the simple instructions (https://github.com/marytts/marytts-installer), but I get the following error message:
```
[root@edchant ~]# cd /tmp/marytts-installer-master
[root@edchant marytts-installer-master]# ./marytts install:cmu-slt
-bash: ./marytts: Permission denied
[root@edchant marytts-installer-master]#
```

Please anybody can advise on this issue.

**Comment by psibre** [comment]
Incidentally, `marytts` is just the Gradle wrapper script [with a custom name](https://docs.gradle.org/current/dsl/org.gradle.api.tasks.wrapper.Wrapper.html#org.gradle.api.tasks.wrapper.Wrapper:scriptFile).
I've heard of issues with a non-executable wrapper script in CI environments, but I'm not sure why it was unzipped as non-executable on your system.
In any case, you can either `chmod +x marytts`, or run it with `sh marytts`.

**Comment by blsn** [comment]
Thank you for your reply,

I tried but I got the following error:
FAILURE: Build failed with an exception.
See below:
```
[root@edchant marytts-installer-master]# chmod +x marytts
[root@edchant marytts-installer-master]# sh marytts
Downloading https://services.gradle.org/distributions/gradle-2.3-bin.zip
...........................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................
Unzipping /root/.gradle/wrapper/dists/gradle-2.3-bin/a48v6zq5mdp1uyn9rwlj56945/gradle-2.3-bin.zip to /root/.gradle/wrapper/dists/gradle-2.3-bin/a48v6zq5mdp1uyn9rwlj56945
Set executable permissions for: /root/.gradle/wrapper/dists/gradle-2.3-bin/a48v6zq5mdp1uyn9rwlj56945/gradle-2.3/bin/gradle
:cmu-slt-hsmm:payload
Download https://jcenter.bintray.com/de/dfki/mary/voice-cmu-slt-hsmm/5.1.2/voice-cmu-slt-hsmm-5.1.2.pom
Download https://jcenter.bintray.com/de/dfki/mary/marytts-common/5.1.2/marytts-common-5.1.2.pom
Download https://jcenter.bintray.com/de/dfki/mary/marytts-runtime/5.1.2/marytts-runtime-5.1.2.pom
Download https://jcenter.bintray.com/de/dfki/mary/marytts-lang-en/5.1.2/marytts-lang-en-5.1.2.pom
Download https://jcenter.bintray.com/de/dfki/mary/marytts-signalproc/5.1.2/marytts-signalproc-5.1.2.pom
Download https://oss.jfrog.org/artifactory/repo/de/dfki/mary/freetts/1.0/freetts-1.0.pom
Download https://oss.jfrog.org/artifactory/repo/de/dfki/mary/freetts-de/1.0/freetts-de-1.0.pom
Download https://oss.jfrog.org/artifactory/repo/de/dfki/mary/freetts-en_us/1.0/freetts-en_us-1.0.pom
Download https://jcenter.bintray.com/de/dfki/mary/voice-cmu-slt-hsmm/5.1.2/voice-cmu-slt-hsmm-5.1.2.jar
Download https://jcenter.bintray.com/de/dfki/mary/marytts-common/5.1.2/marytts-common-5.1.2.jar
Download https://jcenter.bintray.com/de/dfki/mary/marytts-runtime/5.1.2/marytts-runtime-5.1.2.jar
Download https://jcenter.bintray.com/de/dfki/mary/marytts-lang-en/5.1.2/marytts-lang-en-5.1.2.jar
Download https://jcenter.bintray.com/de/dfki/mary/marytts-signalproc/5.1.2/marytts-signalproc-5.1.2.jar
Download https://jcenter.bintray.com/org/slf4j/slf4j-log4j12/1.6.1/slf4j-log4j12-1.6.1.jar
:cmu-slt-hsmm:payload UP-TO-DATE
:cmu-slt-hsmm:verify
Verify  voice-cmu-slt-hsmm-5.1.2.jar
:cmu-slt-hsmm:install
Copy    voice-cmu-slt-hsmm-5.1.2.jar
Copy    marytts-common-5.1.2.jar
Copy    marytts-runtime-5.1.2.jar
Copy    marytts-lang-en-5.1.2.jar
Copy    commons-lang-2.6.jar
Copy    commons-io-2.0.1.jar
Copy    log4j-1.2.16.jar
Copy    marytts-signalproc-5.1.2.jar
Copy    commons-collections-3.2.1.jar
Copy    emotionml-checker-java-1.1.jar
Copy    jtok-core-1.9.1.jar
Copy    freetts-1.0.jar
Copy    freetts-de-1.0.jar
Copy    freetts-en_us-1.0.jar
Copy    guava-14.0.1.jar
Copy    trove4j-2.0.2.jar
Copy    httpcore-4.1.jar
Copy    httpcore-nio-4.1.jar
Copy    opennlp-maxent-3.0.3.jar
Copy    opennlp-tools-1.5.3.jar
Copy    hsqldb-2.0.0.jar
Copy    swing-layout-1.0.3.jar
Copy    slf4j-api-1.6.1.jar
Copy    jwnl-1.3.3.jar
Copy    slf4j-log4j12-1.6.1.jar
:server FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':server'.
> A problem occurred waiting for process 'command '/usr/java/jdk1.8.0_45/bin/java'' to complete.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

Total time: 3 mins 8.608 secs
The message received from the daemon indicates that the daemon has disappeared.
Build request sent: Build{id=d567bb1a-28a3-409b-aa51-4f6949eb132c.1, currentDir=/tmp/marytts-installer-master}
Attempting to read last messages from the daemon log...
Daemon pid: 3614
  log file: /root/.gradle/daemon/2.3/daemon-3614.out.log
----- Last  20 lines from daemon log file - daemon-3614.out.log -----
Total time: 3 mins 8.608 secs
19:16:32.609 [DEBUG] [org.gradle.cache.internal.btree.BTreePersistentIndexedCache] Closing cache taskArtifacts.bin (/tmp/marytts-installer-master/.gradle/2.3/taskArtifacts/taskArtifacts.bin)
19:16:32.613 [DEBUG] [org.gradle.cache.internal.btree.BTreePersistentIndexedCache] Closing cache outputFileStates.bin (/tmp/marytts-installer-master/.gradle/2.3/taskArtifacts/outputFileStates.bin)
19:16:32.613 [DEBUG] [org.gradle.cache.internal.btree.BTreePersistentIndexedCache] Closing cache fileSnapshots.bin (/tmp/marytts-installer-master/.gradle/2.3/taskArtifacts/fileSnapshots.bin)
19:16:32.613 [DEBUG] [org.gradle.cache.internal.btree.BTreePersistentIndexedCache] Closing cache fileHashes.bin (/tmp/marytts-installer-master/.gradle/2.3/taskArtifacts/fileHashes.bin)
19:16:32.614 [DEBUG] [org.gradle.cache.internal.DefaultFileLockManager] Releasing lock on task history cache (/tmp/marytts-installer-master/.gradle/2.3/taskArtifacts).
19:16:32.617 [DEBUG] [org.gradle.cache.internal.DefaultCacheAccess] Cache Plugin Resolution Cache (/root/.gradle/caches/2.3/plugin-resolution) was closed 0 times.
19:16:32.618 [DEBUG] [org.gradle.cache.internal.DefaultFileLockManager] Releasing lock on buildscript class cache for settings file '/tmp/marytts-installer-master/settings.gradle' (/root/.gradle/caches/2.3/scripts/settings_7e4hq6i5adw1pombops2gl78/SettingsScript/buildscript).
19:16:32.621 [DEBUG] [org.gradle.cache.internal.DefaultFileLockManager] Releasing lock on no_buildscript class cache for settings file '/tmp/marytts-installer-master/settings.gradle' (/root/.gradle/caches/2.3/scripts/settings_7e4hq6i5adw1pombops2gl78/SettingsScript/no_buildscript).
19:16:32.621 [DEBUG] [org.gradle.cache.internal.DefaultFileLockManager] Releasing lock on buildscript class cache for build file '/tmp/marytts-installer-master/build.gradle' (/root/.gradle/caches/2.3/scripts/build_7v4d4lgia82lqcfowue1cdecx/ProjectScript/buildscript).
19:16:32.621 [DEBUG] [org.gradle.cache.internal.DefaultFileLockManager] Releasing lock on no_buildscript class cache for build file '/tmp/marytts-installer-master/build.gradle' (/root/.gradle/caches/2.3/scripts/build_7v4d4lgia82lqcfowue1cdecx/ProjectScript/no_buildscript).
19:16:32.622 [DEBUG] [org.gradle.cache.internal.btree.BTreePersistentIndexedCache] Closing cache module-metadata.bin (/root/.gradle/caches/modules-2/metadata-2.14/module-metadata.bin)
19:16:32.622 [DEBUG] [org.gradle.cache.internal.btree.BTreePersistentIndexedCache] Closing cache artifact-at-url.bin (/root/.gradle/caches/modules-2/metadata-2.14/artifact-at-url.bin)
19:16:32.624 [DEBUG] [org.gradle.cache.internal.btree.BTreePersistentIndexedCache] Closing cache artifact-at-repository.bin (/root/.gradle/caches/modules-2/metadata-2.14/artifact-at-repository.bin)
19:16:32.624 [DEBUG] [org.gradle.cache.internal.DefaultFileLockManager] Releasing lock on artifact cache (/root/.gradle/caches/modules-2).
19:16:32.704 [DEBUG] [org.gradle.api.internal.artifacts.ivyservice.ivyresolve.memcache.InMemoryCachedRepositoryFactory] In-memory dependency metadata cache closed. Repos cached: 4, cache instances: 4, modules served from cache: 7, artifacts: 7
19:16:32.708 [DEBUG] [org.gradle.api.internal.artifacts.ivyservice.resolveengine.store.CachedStoreFactory] Resolution result cache closed. Cache reads: 0, disk reads: 0 (avg: 0.0 secs, total: 0.0 secs)
19:16:32.709 [DEBUG] [org.gradle.api.internal.artifacts.ivyservice.resolveengine.store.CachedStoreFactory] Resolved configuration cache closed. Cache reads: 0, disk reads: 0 (avg: 0.0 secs, total: 0.0 secs)
19:16:32.710 [DEBUG] [org.gradle.api.internal.artifacts.ivyservice.resolveengine.store.ResolutionResultsStoreFactory] Deleted 2 resolution results binary files in 0.002 secs
19:16:32.710 [DEBUG] [org.gradle.launcher.daemon.server.exec.ExecuteBuild] The daemon has finished executing the build.
----- End of the daemon log -----


FAILURE: Build failed with an exception.

* What went wrong:
Gradle build daemon disappeared unexpectedly (it may have been killed or may have crashed)

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.
[root@edchant marytts-installer-master]#
```

Please advise,
Thank you,

**Comment by psibre** [comment]
Could you please post the stacktrace of your error?

**Comment by blsn** [comment]
```
[root@edchant marytts-installer-master]# sh marytts --stacktrace
:server
Error occurred during initialization of VM
java.lang.OutOfMemoryError: unable to create new native thread
:server FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':server'.
> Process 'command '/usr/java/jdk1.8.0_45/bin/java'' finished with non-zero exit value 1

* Try:
Run with --info or --debug option to get more log output.

* Exception is:
org.gradle.api.tasks.TaskExecutionException: Execution failed for task ':server'.
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:69)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.execute(ExecuteActionsTaskExecuter.java:46)
        at org.gradle.api.internal.tasks.execution.PostExecutionAnalysisTaskExecuter.execute(PostExecutionAnalysisTaskExecuter.java:35)
        at org.gradle.api.internal.tasks.execution.SkipUpToDateTaskExecuter.execute(SkipUpToDateTaskExecuter.java:64)
        at org.gradle.api.internal.tasks.execution.ValidatingTaskExecuter.execute(ValidatingTaskExecuter.java:58)
        at org.gradle.api.internal.tasks.execution.SkipEmptySourceFilesTaskExecuter.execute(SkipEmptySourceFilesTaskExecuter.java:42)
        at org.gradle.api.internal.tasks.execution.SkipTaskWithNoActionsExecuter.execute(SkipTaskWithNoActionsExecuter.java:52)
        at org.gradle.api.internal.tasks.execution.SkipOnlyIfTaskExecuter.execute(SkipOnlyIfTaskExecuter.java:53)
        at org.gradle.api.internal.tasks.execution.ExecuteAtMostOnceTaskExecuter.execute(ExecuteAtMostOnceTaskExecuter.java:43)
        at org.gradle.api.internal.AbstractTask.executeWithoutThrowingTaskFailure(AbstractTask.java:306)
        at org.gradle.execution.taskgraph.AbstractTaskPlanExecutor$TaskExecutorWorker.executeTask(AbstractTaskPlanExecutor.java:79)
        at org.gradle.execution.taskgraph.AbstractTaskPlanExecutor$TaskExecutorWorker.processTask(AbstractTaskPlanExecutor.java:63)
        at org.gradle.execution.taskgraph.AbstractTaskPlanExecutor$TaskExecutorWorker.run(AbstractTaskPlanExecutor.java:51)
        at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor.process(DefaultTaskPlanExecutor.java:23)
        at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter.execute(DefaultTaskGraphExecuter.java:88)
        at org.gradle.execution.SelectedTaskExecutionAction.execute(SelectedTaskExecutionAction.java:29)
        at org.gradle.execution.DefaultBuildExecuter.execute(DefaultBuildExecuter.java:62)
        at org.gradle.execution.DefaultBuildExecuter.access$200(DefaultBuildExecuter.java:23)
        at org.gradle.execution.DefaultBuildExecuter$2.proceed(DefaultBuildExecuter.java:68)
        at org.gradle.execution.DryRunBuildExecutionAction.execute(DryRunBuildExecutionAction.java:32)
        at org.gradle.execution.DefaultBuildExecuter.execute(DefaultBuildExecuter.java:62)
        at org.gradle.execution.DefaultBuildExecuter.execute(DefaultBuildExecuter.java:55)
        at org.gradle.initialization.DefaultGradleLauncher.doBuildStages(DefaultGradleLauncher.java:149)
        at org.gradle.initialization.DefaultGradleLauncher.doBuild(DefaultGradleLauncher.java:106)
        at org.gradle.initialization.DefaultGradleLauncher.run(DefaultGradleLauncher.java:86)
        at org.gradle.launcher.exec.InProcessBuildActionExecuter$DefaultBuildController.run(InProcessBuildActionExecuter.java:80)
        at org.gradle.launcher.cli.ExecuteBuildAction.run(ExecuteBuildAction.java:33)
        at org.gradle.launcher.cli.ExecuteBuildAction.run(ExecuteBuildAction.java:24)
        at org.gradle.launcher.exec.InProcessBuildActionExecuter.execute(InProcessBuildActionExecuter.java:36)
        at org.gradle.launcher.exec.InProcessBuildActionExecuter.execute(InProcessBuildActionExecuter.java:26)
        at org.gradle.launcher.daemon.server.exec.ExecuteBuild.doBuild(ExecuteBuild.java:48)
        at org.gradle.launcher.daemon.server.exec.BuildCommandOnly.execute(BuildCommandOnly.java:36)
        at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
        at org.gradle.launcher.daemon.server.exec.WatchForDisconnection.execute(WatchForDisconnection.java:37)
        at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
        at org.gradle.launcher.daemon.server.exec.ResetDeprecationLogger.execute(ResetDeprecationLogger.java:26)
        at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
        at org.gradle.launcher.daemon.server.exec.RequestStopIfSingleUsedDaemon.execute(RequestStopIfSingleUsedDaemon.java:34)
        at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
        at org.gradle.launcher.daemon.server.exec.ForwardClientInput$2.call(ForwardClientInput.java:74)
        at org.gradle.launcher.daemon.server.exec.ForwardClientInput$2.call(ForwardClientInput.java:72)
        at org.gradle.util.Swapper.swap(Swapper.java:38)
        at org.gradle.launcher.daemon.server.exec.ForwardClientInput.execute(ForwardClientInput.java:72)
        at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
        at org.gradle.launcher.daemon.server.health.DaemonHealthTracker.execute(DaemonHealthTracker.java:47)
        at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
        at org.gradle.launcher.daemon.server.exec.LogToClient.doBuild(LogToClient.java:60)
        at org.gradle.launcher.daemon.server.exec.BuildCommandOnly.execute(BuildCommandOnly.java:36)
        at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
        at org.gradle.launcher.daemon.server.exec.EstablishBuildEnvironment.doBuild(EstablishBuildEnvironment.java:71)
        at org.gradle.launcher.daemon.server.exec.BuildCommandOnly.execute(BuildCommandOnly.java:36)
        at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
        at org.gradle.launcher.daemon.server.health.HintGCAfterBuild.execute(HintGCAfterBuild.java:41)
        at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
        at org.gradle.launcher.daemon.server.exec.StartBuildOrRespondWithBusy$1.run(StartBuildOrRespondWithBusy.java:50)
        at org.gradle.launcher.daemon.server.DaemonStateCoordinator$1.run(DaemonStateCoordinator.java:246)
        at org.gradle.internal.concurrent.DefaultExecutorFactory$StoppableExecutorImpl$1.run(DefaultExecutorFactory.java:64)
Caused by: org.gradle.process.internal.ExecException: Process 'command '/usr/java/jdk1.8.0_45/bin/java'' finished with non-zero exit value 1
        at org.gradle.process.internal.DefaultExecHandle$ExecResultImpl.assertNormalExitValue(DefaultExecHandle.java:365)
        at org.gradle.process.internal.DefaultJavaExecAction.execute(DefaultJavaExecAction.java:31)
        at org.gradle.api.tasks.JavaExec.exec(JavaExec.java:60)
        at org.gradle.internal.reflect.JavaMethod.invoke(JavaMethod.java:63)
        at org.gradle.api.internal.project.taskfactory.AnnotationProcessingTaskFactory$StandardTaskAction.doExecute(AnnotationProcessingTaskFactory.java:218)
        at org.gradle.api.internal.project.taskfactory.AnnotationProcessingTaskFactory$StandardTaskAction.execute(AnnotationProcessingTaskFactory.java:211)
        at org.gradle.api.internal.project.taskfactory.AnnotationProcessingTaskFactory$StandardTaskAction.execute(AnnotationProcessingTaskFactory.java:200)
        at org.gradle.api.internal.AbstractTask$TaskActionWrapper.execute(AbstractTask.java:585)
        at org.gradle.api.internal.AbstractTask$TaskActionWrapper.execute(AbstractTask.java:568)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeAction(ExecuteActionsTaskExecuter.java:80)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:61)
        ... 56 more


BUILD FAILED

Total time: 13.898 secs
[root@edchant marytts-installer-master]#
```

**Comment by psibre** [comment]
>Error occurred during initialization of VM
java.lang.OutOfMemoryError: unable to create new native thread

How much memory does your system have? And which voices did you install?
