### ISSUE TITLE
Got Exception while executing "./marytts install:cmu-slt"

### ISSUE THREAD

**Issue by ginsi** [marytts/marytts-installer#7]
Trying to install in Raspbian (in Raspberri Pi2), I got the following:
```
pi@raspberrypi:~/marytts-installer-5.2$ ./marytts install:cmu-slt
Downloading https://services.gradle.org/distributions/gradle-2.14.1-bin.zip

Exception in thread "main" javax.net.ssl.SSLException: java.security.ProviderException: java.security.InvalidKeyException: EC parameters error
        at sun.security.ssl.Alerts.getSSLException(Alerts.java:208)
        at sun.security.ssl.SSLSocketImpl.fatal(SSLSocketImpl.java:1914)
        at sun.security.ssl.SSLSocketImpl.fatal(SSLSocketImpl.java:1872)
        at sun.security.ssl.SSLSocketImpl.handleException(SSLSocketImpl.java:1855)
        at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1376)
        at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1353)
        at sun.net.www.protocol.https.HttpsClient.afterConnect(HttpsClient.java:559)
        at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnection.java:185)
        at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1366)
        at sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:263)
        at org.gradle.wrapper.Download.downloadInternal(Download.java:58)
        at org.gradle.wrapper.Download.download(Download.java:44)
        at org.gradle.wrapper.Install$1.call(Install.java:61)
        at org.gradle.wrapper.Install$1.call(Install.java:48)
        at org.gradle.wrapper.ExclusiveFileAccessManager.access(ExclusiveFileAccessManager.java:65)
        at org.gradle.wrapper.Install.createDist(Install.java:48)
        at org.gradle.wrapper.WrapperExecutor.execute(WrapperExecutor.java:107)
        at org.gradle.wrapper.GradleWrapperMain.main(GradleWrapperMain.java:61)
Caused by: java.security.ProviderException: java.security.InvalidKeyException: EC parameters error
....
```
I haven't the slightest idea of what I could do, help please!
Thank you in advance..

**Comment by psibre** [comment]
This is a known issue caused by an incompatibility between Java 7 and the security configuration of services.gradle.org. Please ensure that you're using Java 8.

See also gradle/gradle#2421, or STFW for workarounds.

**Comment by ginsi** [comment]
Thanks for the diagnosis and the suggestion. Of course now I am satisfied and have no interest in further technical comments; but I am not sure if I am supposed to close this now?

**Comment by psibre** [comment]
So everything worked with Java 8?

**Comment by ginsi** [comment]
ehm... well, it was actually "wishful thinking". When I wrote my last comment, I had not yet tried.
I was trying now, but I am a bit confused about versioning.. `java -version` tells me `java version "1.7.0_151"` (I think this means Java 7); on the other hand, when doing `sudo apt-get install oracle-java8-jdk`, i get `oracle-java8-jdk is already the newest version` (??); (probably this show how newbie I am).
In the mean time I found "pico2wave" which - after all - suits my (low) req'ts and installed very easily..
This does not mean I am not interested anymore, only it changed my priorities!
Thanks again..

**Comment by psibre** [comment]
You can set the `JAVA_HOME` environment variable, or try to configure alternatives see https://askubuntu.com/a/388693 or similar.

**Comment by ginsi** [comment]
Eventually (many thanks, psibre, for your support!), I succeeded. Here is the (shortened) log:
```
pi@raspberrypi:~$ # DOWNLOADING INSTALLER
pi@raspberrypi:~$ wget https://github.com/marytts/marytts-installer/archive/v5.2.zip
--2018-01-17 16:23:01--  https://github.com/marytts/marytts-installer/archive/v5.2.zip
...<omissis>...
2018-01-17 16:23:03 (230 KB/s) - v5.2.zip saved [62609]

pi@raspberrypi:~$ UNZIPPING
pi@raspberrypi:~$ unzip v5.2.zip
Archive:  v5.2.zip
...<omissis>...
  inflating: marytts-installer-5.2/settings.gradle 
pi@raspberrypi:~$ # CHECKING INSTALLED CONFIGURATION
pi@raspberrypi:~$ update-alternatives --config java
There are 2 choices for the alternative java (providing /usr/bin/java).

  Selection    Path                                                   Priority   Status
 ------------------------------------------------------------
* 0            /usr/lib/jvm/java-7-openjdk-armhf/jre/bin/java          1063      auto mode
  1            /usr/lib/jvm/java-7-openjdk-armhf/jre/bin/java          1063      manual mode
  2            /usr/lib/jvm/jdk-8-oracle-arm32-vfp-hflt/jre/bin/java   318       manual mode

Press enter to keep the current choice[*], or type selection number:

pi@raspberrypi:~$ # SETTING FOR INSTALLER TO USE JAVA 8
pi@raspberrypi:~$ export JAVA_HOME=/usr/lib/jvm/jdk-8-oracle-arm32-vfp-hflt/
pi@raspberrypi:~$ # GOING TO THE TARGET DIR OF UNZIP
pi@raspberrypi:~$ cd marytts-installer-5.2
pi@raspberrypi:~/marytts-installer-5.2$ # START INSTALLING THE cmu-slt VOICE 
pi@raspberrypi:~/marytts-installer-5.2$ ./marytts install:cmu-slt
Downloading https://services.gradle.org/distributions/gradle-2.14.1-bin.zip
...<omissis>...
BUILD SUCCESSFUL

Total time: 4 mins 38.275 secs
pi@raspberrypi:~/marytts-installer-5.2$ # ET VOICI !
```
